### ISSUE TITLE
0.7 Roadmap

### ISSUE THREAD

**Issue by willtebbutt** [JuliaGaussianProcesses/Stheno.jl#162]
- [x] Complete initial overhaul of internals in #161 
- [x] Re-instate `SparseFiniteGP` functionality
- [x] Update docs with new API + ParameterHandling
- [x] Update examples with new API
- [x] Release 0.7 + announce on discourse

Post-release TODO:
- [x] tidy up tests
- [x] improve test coverage
- [x] reinstate Flux integration tests
